title = "Aslimp"
baseURL = "https://www.aslimpspa.cl"
languageCode = "es"
theme = "aslimp"
resourceDir = "../resources"

DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 12 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  env = "prod"
  favicon = "images/aslimp.jpg"
  site_logo = "images/logos/Aslimp.png"
  description = "Productos de aseo y limpieza."
  facebook = "https://www.facebook.com/aslimp.sap"
  twitter = ""
  instagram = "https://www.instagram.com/aslimp.spa/?hl=es-la"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  whatsapp = ""
  stackoverflow = ""
  rss = ""

  custom_css = ["css/aslimp.css"]
  custom_js = []
  
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-green"
  featured_image = "/images/home-hero-image.jpg"
  recent_posts_number = 2

  #categorias principales para listar en el home
  mainSections = ["baños","bolsas","cocina","covid-19","cuidado-personal","detergentes","multiusos", "papeleria", "pisos", "vidrios"]